import Navbar from "./Navbar"
import { AppProvider, UserProvider } from "./context/context"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <UserProvider>
          {children}
          </UserProvider>
        </AppProvider>
      </body>
    </html>
  )
}
